MangaCentralLibrary/Controllers/PurchaseController.cs
using DatabaseLayer;
using MangaCentralLibrary.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MangaCentralLibrary.Controllers
{
    public class PurchaseController : Controller
    {
        // GET: Purchase
        private MangaCentralLibraryEntities1 db = new MangaCentralLibraryEntities1();
        public ActionResult NewPurchase()
        {
            if (string.IsNullOrEmpty(Convert.ToString(Session["UserID"])))
            {
                return RedirectToAction("Login", "Home");
            }
            double totalamount = 0;
            var temppur = db.PurTemDetailsTables.ToList();
            foreach(var item in temppur)
            {
                totalamount += (item.Qty * item.UnitPrice);
            }
            ViewBag.TotalAmount = totalamount;
            return View(temppur);

        }

        [HttpPost]
        public ActionResult AddItem(int BID, int Qty, float Price)
        {
            if (string.IsNullOrEmpty(Convert.ToString(Session["UserID"])))
            {
                return RedirectToAction("Login", "Home");
            }
            //int userid = Convert.ToInt32(Convert.ToString(Session["UserID"]));
            var find = db.PurTemDetailsTables.Where(i => i.BookID == BID).FirstOrDefault();
            if (find == null)
            {
                if (BID > 0 && Qty > 0 && Price > 0)
                {
                    var newitem = new PurTemDetailsTable()
                    {
                        BookID = BID,
                        Qty = Qty,
                        UnitPrice = Price
                    };
                    db.PurTemDetailsTables.Add(newitem);
                    db.SaveChanges();
                    ViewBag.Message = "Book Added Successfully";
                }
            }
            else
            {
                ViewBag.Message = "Already Exist! Plz Check.";
            }
            return RedirectToAction("NewPurchase");
        }
        public ActionResult DeleteConfirm(int? id)
        {
            if (string.IsNullOrEmpty(Convert.ToString(Session["UserID"])))
            {
                return RedirectToAction("Login", "Home");
            }
            var book = db.PurTemDetailsTables.Find(id);
            if (book != null)
            {
                db.Entry(book).State = System.Data.Entity.EntityState.Deleted;
                db.SaveChanges();
                ViewBag.Message = "Deleted Successfully";
                return RedirectToAction("NewPurchase");
            }
            ViewBag.Message = "Some Unexpected Error Occured";
            return View("NewPurchase");

        }
        [HttpGet]
        public ActionResult GetBooks()
        {
            if (string.IsNullOrEmpty(Convert.ToString(Session["UserID"])))
            {
                return RedirectToAction("Login", "Home");
            }
            List<BookMV> list = new List<BookMV>();
            var booklist = db.BookTables.ToList();
            foreach (var item in booklist)
            {
                list.Add(new BookMV { BookName = item.BookName, BookID = item.BookID });
            }
            return Json(new { data = list }, JsonRequestBehavior.AllowGet);
        }

    }
}

MangaCentralLibrary/Views/Purchase/NewPurchase.cshtml
@model IEnumerable<DatabaseLayer.PurTemDetailsTable>

@{
    ViewBag.Title = "New Purchase";
}
<script src="~/Scripts/jquery-3.3.1.min.js"></script>

@using (Html.BeginForm("AddItem", "Purchase", FormMethod.Post, null))
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <h4>Enter Book Details</h4>
        <hr/>
        @Html.ValidationSummary(true,"",new { @class="text-danger"})

        <div class="form-group">
            <label class="control-label col-md-2">Select Book</label>
            <div class="col-md-6">
                <select class="form-control" id="BID" name="BID" required></select>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2">Quantity</label>
            <div class="col-md-6">
                <input type="number" class="form-control" id="Qty" name="Qty" placeholder="Enter Purchase Qty..." required />
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2">Unit Price</label>
            <div class="col-md-6">
                <input type="number" class="form-control" id="Price" step=".01" name="Price" placeholder="Enter Price..." required />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Add Item" class="btn btn-success"/>
            </div>
        </div>
    </div>
}


<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Purchase Items List</h6>
        <h3 class="text-danger">@ViewBag.Message</h3>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>
                            Book
                        </th>
                        <th>
                            Purchase Qty
                        </th>
                        <th>
                            Unit Price
                        </th>
                        <th>
                            Item Cost
                        </th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.BookTable.BookName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Qty)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.UnitPrice)
                            </td>
                            <td>
                                @(string.Format("{0:0.000}", Math.Truncate(item.Qty *item.UnitPrice * 10) /10)) INR
                            </td>

                            <td class="btn-group">
                                @Html.ActionLink("Delete", "DeleteConfirm", new { id = item.PurTemID }, new { @class = "btn btn-danger" })
                            </td>
                        </tr>
                        }
                </tbody>
                <tfoot>
                    <tr>
                       <td></td>
                        <td></td>
                        <td style="background-color:crimson; color:black;"><strong>Total</strong></td>
                        <td style="background-color:crimson; color:cyan;">
                            @(string.Format("{0:0.000}", Math.Truncate(ViewBag.TotalAmount * 10) / 10)) INR
                        </td>
                        <td></td>
                    </tr>
                </tfoot>
            </table>
            <div style="margin-top:20px;float:right">
                @Html.ActionLink("Next", "SelectSupplier", null,new { @class = "btn btn-success", style = "padding:20px;" })
                @Html.ActionLink("Cancel","CancelPurchase",null,new { @class = "btn btn-danger", style = "padding:20px" })

            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function () {
        $.ajax({
            url: '@Url.Action("GetBooks", "Purchase")',
            type: 'GET',
            data: "{}",
            success: function (response) {
                for (var i = 0; i < response.data.length; i++) {
                    $('#BID').append("<option value=" + response.data[i].BookID + ">" + response.data[i].BookName + "</option>");
                }
            },
            error: function () { }
        });
    });
</script>